stages:
  - build
  - test

build_job:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew build

test_job:
  stage: test
  script:
    - chmod +x ./gradlew
    - ./gradlew test
