stages:
  - build
  - test

build_job:
  stage: build
  image: openjdk:11-jdk-slim
  script:
    - chmod +x ./gradlew
    - ./gradlew build

test_job:
  stage: test
  image: openjdk:11-jdk-slim
  script:
    - chmod +x ./gradlew
    - ./gradlew test
